#!/bin/sh

set -e
set -u
set -x

die() {
    echo "$@"
    exit 1
}

# First, ensure Valgrind works:
if [ ! "$(command -v valgrind)" ] ; then
    die "Valgrind does not appear to be in \$PATH"
fi

if [ -x /bin/true ] ; then
    TRUE="/bin/true"
elif [ -x /usr/bin/true ] ; then
    TRUE="/usr/bin/true"
else
    die "Couldn't find true binary!"
fi

valgrind "$TRUE" || die "Valgrind failed for $TRUE"

# Now, check that individual files are working:
for file in valgrind-suppressions-*
do
    valgrind --suppressions="$file" "$TRUE" || die "file $file appears broken"
done

echo "Tests succeeded"
